- hosts: all
  vars:
    hello_msg: Hello from Ricardo!!!
  tasks:
  - win_copy:
      content: "{{ hello_msg }}"
      dest: "{{ ansible_facts['user_dir'] }}\\Desktop\\hello.txt"
  - fail: "Sorry, I found a problem and can't continue."