- hosts: Workstations
  tasks:
  - win_copy:
      content: "{{ ansible_facts | to_nice_yaml }}"
      dest: "{{ ansible_facts['user_dir'] }}\\Desktop\\facts.txt"
  - win_template:
      src: report.txt.j2
      dest: "{{ ansible_facts['user_dir'] }}\\Desktop\\report.txt"
